# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*']        # autorise toutes les origines
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            # Hérite des defaults